// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVi-O-GXbfWRfCwfwZjrjeBLM86dZPhI',
    appId: '1:748687271183:web:1342ab1de5487593a70a7a',
    messagingSenderId: '748687271183',
    projectId: 'nursecare-4613f',
    authDomain: 'nursecare-4613f.firebaseapp.com',
    databaseURL: 'https://nursecare-4613f-default-rtdb.firebaseio.com',
    storageBucket: 'nursecare-4613f.appspot.com',
    measurementId: 'G-T21Y1F38LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRcyjS6KKnMG-7F3dNTxl0CBO3h4CIa7E',
    appId: '1:748687271183:android:57602b51d0dce1e3a70a7a',
    messagingSenderId: '748687271183',
    projectId: 'nursecare-4613f',
    databaseURL: 'https://nursecare-4613f-default-rtdb.firebaseio.com',
    storageBucket: 'nursecare-4613f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfuKMqYGBrWeKEz_r7HxktB-OGMzrvmM8',
    appId: '1:748687271183:ios:3be3ac1eb34dd198a70a7a',
    messagingSenderId: '748687271183',
    projectId: 'nursecare-4613f',
    databaseURL: 'https://nursecare-4613f-default-rtdb.firebaseio.com',
    storageBucket: 'nursecare-4613f.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfuKMqYGBrWeKEz_r7HxktB-OGMzrvmM8',
    appId: '1:748687271183:ios:3be3ac1eb34dd198a70a7a',
    messagingSenderId: '748687271183',
    projectId: 'nursecare-4613f',
    databaseURL: 'https://nursecare-4613f-default-rtdb.firebaseio.com',
    storageBucket: 'nursecare-4613f.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGVi-O-GXbfWRfCwfwZjrjeBLM86dZPhI',
    appId: '1:748687271183:web:90282c40eb8d8325a70a7a',
    messagingSenderId: '748687271183',
    projectId: 'nursecare-4613f',
    authDomain: 'nursecare-4613f.firebaseapp.com',
    databaseURL: 'https://nursecare-4613f-default-rtdb.firebaseio.com',
    storageBucket: 'nursecare-4613f.appspot.com',
    measurementId: 'G-E6XDVVNJ6L',
  );

}